### PR TITLE
relax dependencies

### PR DESCRIPTION
**Pull request by gfx**
The latest cropperjs version is 1.1.3 with some bug fixes from 1.0.0-rc3: https://github.com/fengyuanchen/cropperjs/releases

### CODE REVIEW

**Comment by ThomsCass** [comment]
The latest is v1.3.4 now !

**Comment by salim7** [comment]
Is this project dead?

**Comment by gfx** [comment]
@roadmanfong ping

**Comment by schuylr** [comment]
@roadmanfong The outdated dependency of `cropperjs` breaks modern transpilers like babel-loader. Please consider maintaining your library or opening it up to other contributors.

**Comment by roadmanfong** [comment]
updated

**Pull request closed without merging**
